### ISSUE TITLE
vtkgdcm

### ISSUE THREAD

**Issue by ljsalvatierra** [malaterre/GDCM#15]
Machine
====

```bash
$ uname -a
Linux ubuntu-desktop 3.19.0-25-generic #26-Ubuntu SMP Fri Jul 24 21:17:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid
$ cat /proc/cpuinfo
...
processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
stepping	: 3
microcode	: 0x19
cpu MHz		: 1118.593
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 
clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc 
arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni 
pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 
sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm 
abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase 
tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm xsaveopt
bugs		:
bogomips	: 8000.29
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
$ cat /proc/meminfo
MemTotal:        8115528 kB
MemFree:          146228 kB
MemAvailable:    6072416 kB
Buffers:         2247788 kB
Cached:          3719328 kB
SwapCached:          828 kB
Active:          1952800 kB
Inactive:        5219296 kB
Active(anon):     427460 kB
Inactive(anon):   824568 kB
Active(file):    1525340 kB
Inactive(file):  4394728 kB
Unevictable:          32 kB
Mlocked:              32 kB
SwapTotal:       3998204 kB
SwapFree:        3979584 kB
Dirty:               584 kB
Writeback:             0 kB
AnonPages:       1215532 kB
Mapped:           542308 kB
Shmem:             46600 kB
Slab:             344872 kB
SReclaimable:     259524 kB
SUnreclaim:        85348 kB
KernelStack:       10080 kB
PageTables:        31428 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     8055968 kB
Committed_AS:    5135916 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      309552 kB
VmallocChunk:   34359424036 kB
HardwareCorrupted:     0 kB
AnonHugePages:    278528 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      177772 kB
DirectMap2M:     3956736 kB
DirectMap1G:     4194304 kB
```

GDCM-Build with CMake
====

```bash
GDCM_BUILD_APPLICATIONS          ON                                                                                                                                                                                
 GDCM_BUILD_EXAMPLES              ON                                                                                                                                                                                
 GDCM_BUILD_SHARED_LIBS           ON                                                                                                                                                                                
 GDCM_BUILD_TESTING               ON                                                                                                                                                                                
 GDCM_DOCUMENTATION               ON                                                                                                                                                                                
 GDCM_USE_VTK                     ON                                                                                                                                                                                
 GDCM_WRAP_CSHARP                 OFF                                                                                                                                                                               
 GDCM_WRAP_JAVA                   OFF                                                                                                                                                                               
 GDCM_WRAP_PHP                    OFF                                                                                                                                                                               
 GDCM_WRAP_PYTHON                 ON                                                                                                                                                                                
 Qt5Core_DIR                      /usr/lib/x86_64-linux-gnu/cmake/Qt5Core                                                                                                                                           
 Qt5Gui_DIR                       /usr/lib/x86_64-linux-gnu/cmake/Qt5Gui                                                                                                                                            
 Qt5Network_DIR                   /usr/lib/x86_64-linux-gnu/cmake/Qt5Network                                                                                                                                        
 Qt5WebKit_DIR                    /usr/lib/x86_64-linux-gnu/cmake/Qt5WebKit
```

Error
====

```bash
[ 50%] Linking CXX shared library ../../bin/libgdcmMEXD.so
[ 50%] Built target gdcmMEXD
Scanning dependencies of target vtkgdcm
[ 50%] Building CXX object Utilities/VTK/CMakeFiles/vtkgdcm.dir/vtkGDCMTesting.cxx.o
In file included from /home/ljsalvatierra/bin/gdcm/Utilities/VTK/vtkGDCMTesting.cxx:14:0:
/home/ljsalvatierra/bin/gdcm/Utilities/VTK/vtkGDCMTesting.h:30:48: error: ISO C++ forbids declaration of ‘vtkTypeRevisionMacro’ with no type [-fpermissive]
   vtkTypeRevisionMacro(vtkGDCMTesting,vtkObject);
                                                ^
/home/ljsalvatierra/bin/gdcm/Utilities/VTK/vtkGDCMTesting.cxx:21:37: error: expected identifier before string constant
 vtkCxxRevisionMacro(vtkGDCMTesting, "$Revision: 1.31 $")
                                     ^
/home/ljsalvatierra/bin/gdcm/Utilities/VTK/vtkGDCMTesting.cxx:21:37: error: expected ‘,’ or ‘...’ before string constant
In file included from /home/ljsalvatierra/bin/gdcm/Utilities/VTK/vtkGDCMTesting.cxx:16:0:
/home/ljsalvatierra/bin/gdcm/Utilities/VTK/vtkGDCMTesting.cxx:22:21: error: expected constructor, destructor, or type conversion before ‘vtkGDCMTesting’
 vtkStandardNewMacro(vtkGDCMTesting)
                     ^
/usr/local/include/vtk-6.3/vtkObjectFactory.h:322:3: note: in definition of macro ‘vtkStandardNewMacro’
   thisClass* thisClass::New() \
   ^
Utilities/VTK/CMakeFiles/vtkgdcm.dir/build.make:62: recipe for target 'Utilities/VTK/CMakeFiles/vtkgdcm.dir/vtkGDCMTesting.cxx.o' failed
make[2]: *** [Utilities/VTK/CMakeFiles/vtkgdcm.dir/vtkGDCMTesting.cxx.o] Error 1
CMakeFiles/Makefile2:1505: recipe for target 'Utilities/VTK/CMakeFiles/vtkgdcm.dir/all' failed
make[1]: *** [Utilities/VTK/CMakeFiles/vtkgdcm.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ljsalvatierra** [comment]
I'm trying to modify GDCM to work with VTK 6.3, following this:

www.mitk.org/wiki/VTK6_Migration_Guide

But I'm not able to fix this other problem:
```bash
/home/ljsalvatierra/bin/gdcm/Utilities/VTK/vtkGDCMImageWriter.cxx: In member function ‘int vtkGDCMImageWriter::WriteGDCMData(vtkImageData*, int)’:
/home/ljsalvatierra/bin/gdcm/Utilities/VTK/vtkGDCMImageWriter.cxx:661:32: error: no matching function for call to ‘vtkImageData::GetScalarRange(float [2])’
     data->GetScalarRange(srange);
                                ^
/home/ljsalvatierra/bin/gdcm/Utilities/VTK/vtkGDCMImageWriter.cxx:661:32: note: candidates are:
In file included from /usr/local/include/vtk-6.3/vtkImageData.h:26:0,
                 from /home/ljsalvatierra/bin/gdcm/Utilities/VTK/vtkGDCMImageWriter.cxx:18:
/usr/local/include/vtk-6.3/vtkDataSet.h:279:16: note: virtual void vtkDataSet::GetScalarRange(double*)
   virtual void GetScalarRange(double range[2]);
                ^
/usr/local/include/vtk-6.3/vtkDataSet.h:279:16: note:   no known conversion for argument 1 from ‘float [2]’ to ‘double*’
/usr/local/include/vtk-6.3/vtkDataSet.h:289:11: note: double* vtkDataSet::GetScalarRange()
   double *GetScalarRange();
           ^
/usr/local/include/vtk-6.3/vtkDataSet.h:289:11: note:   candidate expects 0 arguments, 1 provided
/home/ljsalvatierra/bin/gdcm/Utilities/VTK/vtkGDCMImageWriter.cxx:784:32: error: no matching function for call to ‘vtkImageData::GetScalarRange(float [2])’
     data->GetScalarRange(srange);
                                ^
/home/ljsalvatierra/bin/gdcm/Utilities/VTK/vtkGDCMImageWriter.cxx:784:32: note: candidates are:
In file included from /usr/local/include/vtk-6.3/vtkImageData.h:26:0,
                 from /home/ljsalvatierra/bin/gdcm/Utilities/VTK/vtkGDCMImageWriter.cxx:18:
/usr/local/include/vtk-6.3/vtkDataSet.h:279:16: note: virtual void vtkDataSet::GetScalarRange(double*)
   virtual void GetScalarRange(double range[2]);
                ^
/usr/local/include/vtk-6.3/vtkDataSet.h:279:16: note:   no known conversion for argument 1 from ‘float [2]’ to ‘double*’
/usr/local/include/vtk-6.3/vtkDataSet.h:289:11: note: double* vtkDataSet::GetScalarRange()
   double *GetScalarRange();
           ^
/usr/local/include/vtk-6.3/vtkDataSet.h:289:11: note:   candidate expects 0 arguments, 1 provided
/home/ljsalvatierra/bin/gdcm/Utilities/VTK/vtkGDCMImageWriter.cxx:1086:59: error: cannot convert ‘double*’ to ‘const float*’ in initialization
   const vtkFloatingPointType *vtkorigin = data->GetOrigin();
                                                           ^
Utilities/VTK/CMakeFiles/vtkgdcm.dir/build.make:110: recipe for target 'Utilities/VTK/CMakeFiles/vtkgdcm.dir/vtkGDCMImageWriter.cxx.o' failed
make[2]: *** [Utilities/VTK/CMakeFiles/vtkgdcm.dir/vtkGDCMImageWriter.cxx.o] Error 1
CMakeFiles/Makefile2:1505: recipe for target 'Utilities/VTK/CMakeFiles/vtkgdcm.dir/all' failed
make[1]: *** [Utilities/VTK/CMakeFiles/vtkgdcm.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

By the way, nice one hahaha:
```C++
    // HACK !!!
    // MR Image Storage cannot have Shift / Rescale , however it looks like people are doing it
    // anyway, so let's make GDCM just as bad as any other library, by providing a fix:
    if( ms == gdcm::MediaStorage::MRImageStorage /*&& pixeltype.GetBitsAllocated() == 8*/ )
```
