### PR TITLE
Fix Python wrappers for SWIG 4.5.0

### PR DESCRIPTION
**Pull request by lahwaacz**
GDCM fails to compile with SWIG 4.5.0, which removed the Python 2 compatibility aliases, causing compiler errors like

    error: 'PyString_AsString' was not declared in this scope
    error: 'PyInt_FromLong' was not declared in this scope

Since Python 2 is long dead, these should be replaced in the hand-written gdcmswig.i and gdcmcommon.i files.

### CODE REVIEW

**Comment by exoosh** [comment]
Yep, I also had pointed this out earlier. The Python detection itself is still Python 2.x as far as I recall (see d528f5e52df830c76e849e3e7e54481e3398d8e2).
